name: mobile_wallet
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  web_socket_channel: ^2.3.0
  flutter:
    sdk: flutter
  flutter_credit_card: ^4.0.0+1
  cupertino_icons: ^1.0.8
  intl: ^0.18.0 # Add the intl package for date formatting
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  flutter_barcode_scanner: ^2.0.0
  qr_flutter: ^4.0.0
  image_picker: ^0.8.8+7
  qr_code_tools: ^0.1.0
  zxing2: ^0.2.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/purple.jpg
    - assets/LOGO.png
    - assets/noon.png
    - assets/hm.png
    # Ensure this file exists in the 'images' directory of your project





